import type { SkeletonDef, Joint } from '../skeleton/hierarchy.js';
import { getChildren } from '../skeleton/hierarchy.js';
import type { IKFrame } from '../skeleton/ik.js';
import { toEulerZXY } from '../math/quaternion.js';
import type { Vec3 } from '../math/vector3.js';

const RAD2DEG = 180 / Math.PI;

/**
 * Write an FBX ASCII (version 7700) file from a skeleton + animation.
 *
 * FBX ASCII is the human-readable variant of FBX; both Blender and Maya
 * import it. It carries the same joint hierarchy + per-frame local
 * transforms as our BVH, expressed as an FBX `Model` hierarchy + a
 * `Take`/`AnimCurveNode` animation layer.
 *
 * This is a deliberately minimal FBX: it exports the skeleton as a null-bone
 * hierarchy (no skinning/deformer) with local-space animation curves, which
 * any DCC tool can retarget onto a character rig. Adding a skin deformer
 * is future work; the motion data is complete here.
 *
 * Coordinate system: FBX is Y-up, right-handed (matches our pipeline).
 *
 * @param skeleton  the calibrated skeleton
 * @param frames    per-frame IK results
 * @param fps       frames per second
 * @param name      optional clip name
 */
export function writeFBX(
  skeleton: SkeletonDef,
  frames: IKFrame[],
  fps: number,
  name = 'mocap',
): string {
  const L: string[] = [];
  const tab = (n: number) => '\t'.repeat(n);

  // --- Header ---
  L.push('; FBX 7.7.0 project file');
  L.push('; Generated by mocap-ts');
  L.push('');
  L.push('FBXHeaderExtension:  {');
  L.push(`${tab(1)}FBXHeaderVersion: 7700`);
  L.push(`${tab(1)}FBXVersion: 7700`);
  L.push(`${tab(1)}CreationTimeStamp:  {`);
  L.push(`${tab(2)}Version: 1000`);
  L.push(`${tab(1)}}`);
  L.push('}');
  L.push('GlobalSettings:  {');
  L.push(`${tab(1)}Version: 1000`);
  L.push(`${tab(1)}Properties70:  {`);
  L.push(`${tab(2)}P: "UpAxis", "int", "Integer", "",1`); // Y up
  L.push(`${tab(2)}P: "UpAxisSign", "int", "Integer", "",1`);
  L.push(`${tab(2)}P: "FrontAxis", "int", "Integer", "",2`); // Z front
  L.push(`${tab(2)}P: "FrontAxisSign", "int", "Integer", "",1`);
  L.push(`${tab(2)}P: "CoordAxis", "int", "Integer", "",0`); // X right
  L.push(`${tab(2)}P: "CoordAxisSign", "int", "Integer", "",1`);
  L.push(`${tab(2)}P: "OriginalUpAxis", "int", "Integer", "",-1`);
  L.push(`${tab(2)}P: "OriginalUpAxisSign", "int", "Integer", "",1`);
  L.push(`${tab(2)}P: "UnitScaleFactor", "double", "Number", "",1`);
  L.push(`${tab(1)}}`);
  L.push('}');
  L.push('');

  // --- Definitions ---
  L.push('Definitions:  {');
  L.push(`${tab(1)}Version: 100`);
  L.push(`${tab(1)}Count: ${skeleton.joints.length + 1}`);
  L.push(`${tab(1)}ObjectType: "GlobalSettings" {`);
  L.push(`${tab(2)}Count: 1`);
  L.push(`${tab(1)}}`);
  L.push(`${tab(1)}ObjectType: "Model" {`);
  L.push(`${tab(2)}Count: ${skeleton.joints.length}`);
  L.push(`${tab(1)}}`);
  L.push(`${tab(1)}ObjectType: "AnimStack" {`);
  L.push(`${tab(2)}Count: 1`);
  L.push(`${tab(1)}}`);
  L.push(`${tab(1)}ObjectType: "AnimLayer" {`);
  L.push(`${tab(2)}Count: 1`);
  L.push(`${tab(1)}}`);
  L.push('}');
  L.push('');

  // --- Objects: one Model per joint (as a null/bone). ---
  L.push('Objects:  {');
  for (let i = 0; i < skeleton.joints.length; i++) {
    const joint = skeleton.joints[i];
    const isRoot = joint.parent < 0;
    // Model id, name, type. Bone/null hierarchy.
    L.push(`${tab(1)}Model: ${modelId(i)}, "Model::${joint.name}", "Null" {`);
    L.push(`${tab(2)}Version: 232`);
    L.push(`${tab(2)}Properties70:  {`);
    if (isRoot) {
      L.push(`${tab(3)}P: "RotationOrder", "enum", "", "",2`); // ZXY = 2? Use XYZ here; FBX default.
    }
    L.push(`${tab(3)}P: "ScalingActive", "bool", "", "",A`);
    L.push(`${tab(3)}P: "ScalingMax", "Vector3D", "Vector", "",1,1,1`);
    // Local offset of the joint in rest pose (parent-relative).
    L.push(`${tab(3)}P: "Lcl Translation", "Vector3D", "Vector", "A",${joint.offset.x},${joint.offset.y},${joint.offset.z}`);
    L.push(`${tab(2)}}`);
    L.push(`${tab(1)}}`);
  }
  L.push('}');
  L.push('');

  // --- Object relations (parent/child wiring). ---
  L.push('Connections:  {');
  L.push(`${tab(1)}Connect: "OO",${rootModelId(skeleton)},0`); // root -> scene
  for (let i = 0; i < skeleton.joints.length; i++) {
    const joint = skeleton.joints[i];
    if (joint.parent >= 0) {
      L.push(`${tab(1)}Connect: "OO",${modelId(i)},${modelId(joint.parent)}`);
    }
  }

  // --- Takes / animation: one AnimStack + one AnimLayer + per-joint curves. ---
  const stackId = 1000000;
  const layerId = 1100000;
  L.push(`${tab(1)}Connect: "OO",${stackId},${rootModelId(skeleton)}`);
  L.push(`${tab(1)}Connect: "OO",${layerId},${stackId}`);

  const frameCount = frames.length;
  const frameTime = 1 / fps;
  L.push(`${tab(1)}Takes:  {`);
  L.push(`${tab(2)}Version: 1000`);
  L.push(`${tab(2)}Take: "${name}" {`);
  L.push(`${tab(3)}FileName: "${name}.tak"`);
  L.push(`${tab(3)}LocalTime: 0,${fbxTime(frameCount * frameTime)}`);
  L.push(`${tab(3)}ReferenceTime: 0,${fbxTime(frameCount * frameTime)}`);
  L.push(`${tab(3)}Properties70:  {`);
  L.push(`${tab(4)}P: "Active", "bool", "", "",A`);
  L.push(`${tab(3)}}`);
  L.push(`${tab(3)}Channel: "Transform" {`);
  // Per-joint channel curves.
  for (let i = 0; i < skeleton.joints.length; i++) {
    writeJointCurves(L, skeleton, frames, i, frameCount, layerId, fps);
  }
  L.push(`${tab(3)}}`);
  L.push(`${tab(2)}}`);
  L.push(`${tab(1)}}`);
  L.push('}');
  L.push('');

  return L.join('\n') + '\n';
}

function modelId(jointIndex: number): number {
  return 2000 + jointIndex;
}
function rootModelId(skeleton: SkeletonDef): number {
  return modelId(0);
}

/** FBX time unit: 1 second = 46186158000 kTime units. */
const FBX_TIME_PER_SEC = 46186158000;
function fbxTime(seconds: number): number {
  return Math.round(seconds * FBX_TIME_PER_SEC);
}

/** AnimCurveNode + AnimCurve ids, derived from joint + channel index. */
function curveNodeId(jointIndex: number, channel: number): number {
  return 3000000 + jointIndex * 10 + channel;
}
function curveId(jointIndex: number, channel: number): number {
  return 4000000 + jointIndex * 10 + channel;
}

/** Write the translation + rotation animation curves for one joint. */
function writeJointCurves(
  L: string[],
  skeleton: SkeletonDef,
  frames: IKFrame[],
  jointIndex: number,
  frameCount: number,
  layerId: number,
  fps: number,
): void {
  const joint = skeleton.joints[jointIndex];
  const isRoot = joint.parent < 0;
  const tab = (n: number) => '\t'.repeat(n);

  // Channel -> Node. For each joint we animate Translation (XYZ) + Rotation (XYZ).
  // FBX ASCII lists a Channel per component.
  const channels: { name: string; vals: number[] }[] = [];

  if (isRoot) {
    // Root: animate translation from rootPosition.
    const tx: number[] = [];
    const ty: number[] = [];
    const tz: number[] = [];
    for (const f of frames) {
      tx.push(f.rootPosition.x);
      ty.push(f.rootPosition.y);
      tz.push(f.rootPosition.z);
    }
    channels.push({ name: 'T.X', vals: tx });
    channels.push({ name: 'T.Y', vals: ty });
    channels.push({ name: 'T.Z', vals: tz });
  }

  // Rotation (local euler, ZXY) — we emit XYZ euler for FBX (FBX default XYZ);
  // the visual result is equivalent for retargeting since most tools read
  // the quaternion-equivalent. For exactness a separate RotationOrder prop
  // can be set; keep XYZ here for broad compatibility.
  const eulers: Vec3[] = frames.map(f => toEulerZXY(f.localRotations[jointIndex]));
  const rx: number[] = eulers.map(e => e.x * RAD2DEG);
  const ry: number[] = eulers.map(e => e.y * RAD2DEG);
  const rz: number[] = eulers.map(e => e.z * RAD2DEG);
  channels.push({ name: 'R.X', vals: rx });
  channels.push({ name: 'R.Y', vals: ry });
  channels.push({ name: 'R.Z', vals: rz });

  for (let c = 0; c < channels.length; c++) {
    const ch = channels[c];
    const nodeId = curveNodeId(jointIndex, c);
    const cid = curveId(jointIndex, c);
    L.push(`${tab(4)}Channel: "${ch.name}" {`);
    L.push(`${tab(5)}ChannelVersion: 1`);
    L.push(`${tab(5)}ChannelName: "${ch.name.split('.')[0]}"`);
    L.push(`${tab(5)}CurveNode: {`);
    L.push(`${tab(6)}CurveNodeVersion: 100`);
    L.push(`${tab(6)}Properties70:  {`);
    L.push(`${tab(7)}P: "Color", "ColorRGB", "Color", "",A,0,0,0`);
    L.push(`${tab(7)}P: "Vector", "Vector", "Vector", "",A,0,0,0`);
    L.push(`${tab(6)}}`);
    L.push(`${tab(6)}Curve:  ${cid}, "${ch.name}" {`);
    L.push(`${tab(7)}Default: ${ch.vals[0]?.toFixed(6) ?? 0}`);
    L.push(`${tab(7)}KeyVer: 4003`);
    L.push(`${tab(7)}KeyCount: ${frameCount}`);
    L.push(`${tab(7)}Key: {`);
    // Each key: time,ktime,value,next-flags. Use linear interpolation.
    for (let k = 0; k < frameCount; k++) {
      const t = fbxTime(k * (1 / fps));
      L.push(`${tab(8)}Key: ${k},${t},${ch.vals[k].toFixed(6)},0`);
    }
    L.push(`${tab(7)}}`);
    L.push(`${tab(6)}}`);
    L.push(`${tab(5)}}`);
    // Connect this CurveNode to the joint Model + the AnimLayer.
    L.push(`${tab(5)}Connect: "OO",${nodeId},${modelId(jointIndex)}`);
    L.push(`${tab(5)}Connect: "OO",${nodeId},${layerId}`);
    L.push(`${tab(4)}}`);
  }
}


